postgres:
    dialect: postgres
    datasource: dbname=test sslmode=disable
    dir: test-migrations

postgres_env:
    dialect: postgres
    datasource: host=${PG_HOST} dbname=${PG_NAME} user=${PG_USER} password=${PG_PASS} sslmode=disable
    dir: ${APP_DIR}/test-migrations

mysql:
    dialect: mysql
    datasource: root@/test?parseTime=true
    dir: test-migrations

mysql_noflag:
    dialect: mysql
    datasource: root@/test
    dir: test-migrations

mysql_env:
    dialect: mysql
    datasource: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${DATABASE_NAME}?parseTime=true
    dir: test-migrations

sqlite:
    dialect: sqlite3
    datasource: test.db
    dir: test-migrations
    table: migrations
